### ISSUE TITLE
[Feature Request] ProjectRed mod suite integration 

### ISSUE THREAD

**Issue by Caldoric** [dannydjdk/Tiny-Redstone#102]
As the title implies, I'd love to see some deeper compatibility/integration between the "Tiny Redstone" and "ProjectRed" mod suites. Specifically, it would be nice to be able to have "tiny" versions of some of the PR items available for use with the rest of the tiny redstone components. Sure, there's some redundancy between "Tiny Gates" and "ProjectRed - Integration", but the main thing I'm after is the idea of tiny versions of red alloy wires (insulated and non-insulated) as well as the "busses" that you can make with the PR suite. I'm aware Tiny Redstone is based on the old "Super Circuit Maker" mod, which used to have busses and colored Redstone lines of its own, so it'd be nice to see those come back, even if it's via connection to an external set of mods. Heck, maybe even make it an addon if need be, instead of integrating it directly into the core mod of the Tiny Redstone suite.

**Comment by dannydjdk** [comment]
Thanks for the suggestions!

I want to make one thing clear first. While Tiny Redstone was inspired by Super Circuit Maker, it is not, in any way, based on it. It's a completely separate code base built from the ground up, and the features are much more closely related to vanilla redstone than to SCM. The aim of this mod is to replicate vanilla redstone behavior as closely as possible, which is why I chose to use add-on mods for Tiny Gates, Ranged Wireless Redstone and Tiny Pipes.

I think that Tiny Redstone Dust already acts almost identically to Red Alloy Wires. The Redstone Pipes in Tiny Pipes add-on essentially function as insulated redstone wires that can carry up to 16 different redstone signals. Let me know if there are any other specific features that you're looking for. Most likely, they would be considered for one of the add-on mods.
