### ISSUE TITLE
[bug] Redstone doesn't turn off after a pulse from a outside block

### ISSUE THREAD

**Issue by Vo1d88** [dannydjdk/Tiny-Redstone#117]
when I place the redstone to get the signal from a pulsating block, after the pulse the redstone doesn't turn off.
![2023-01-24_15 43 04](https://user-images.githubusercontent.com/123479379/214325757-0ae4930a-d1ae-4fbb-8f18-3f37b3dcb47e.png)
![2023-01-24_15 54 20](https://user-images.githubusercontent.com/123479379/214327780-03a2204c-6d00-4334-803d-edb893f56460.png)
![2023-01-24_15 54 29](https://user-images.githubusercontent.com/123479379/214327785-0eb4932a-85e2-4793-a50f-eb426b29d9e4.png)

mc 1.19.2
tinyredstone-1.19.2-4.1.2

**Comment by Vo1d88** [comment]
in here,
![2023-01-24_16 17 26](https://user-images.githubusercontent.com/123479379/214333971-493a79ac-2165-47b0-9b26-ede92cd1118b.png)
 it doesn't recognise the pulse when it is placed on the panel, because I think the pulse is to short.

**Comment by dannydjdk** [comment]
Thanks for the report!

**Cyclic Clock Issue**
The solution is for Tiny Redstone to treat this block as if its a Redstone wire. This can be done in the server config by adding "cyclic:clock" to the redstone_wires setting. If you know of other Cyclic blocks that cause the same problem, please let me know so I can add them to the default configs for Tiny Redstone.

Here are the details behind the problem:
The Cyclic Clock is allowing indirect signals to be read through them. This is usually undesired behavior for Redstone sources for this exact reason. Since Redstone wires pass signals in both directions, when a redstone source allows redstone to pass through, when its signal is lost, both blocks continue to read each other's signal. I suspect other mods with two way redstone wires will probably run into the same issue with this block.

Vanilla redstone does a trick where it temporarily disabled output of every redstone dust block in the world while it reads indirect signals, so that it can prevent this. Thats why it works when a vanilla redstone dust is in between. But, it's not really possible for mods to do this.

**Tiny Gates Clock Issue**
This issue is actually visual only. A signal is passing through, but by the time the client refreshes, it has already passed. If you place a tiny repeater facing away from the tiny redstone lamp, you will see it pulse. Therefore, it should have no affect on redstone logic.

Strangely, it seems related specifically to signals coming from the East direction. The existence or non-existence of the panel shouldn't really affect anything. Though I don't fully understand the significance of the East direction, this is probably one reason why Redstone ticks in vanilla are 2 game ticks in length. 

(TODO) I'll look into lengthening the pulse of the Tiny Gates clock. In the meantime, a repeater will lengthen it for you as a quick solution. Even without that though, any redstone logic depending on that clock should work as expected.

I appreciate your report. It helps me make Tiny Restone better!
