### ISSUE TITLE
 [Forge 1.18.2] Tiny Redstone one-tick signals behave differently depending on its direction.

### ISSUE THREAD

**Issue by FoxyFox909** [dannydjdk/Tiny-Redstone#120]
Hello it's me again. I appreciate your super fast bugfix for the prior issue, and I honestly feel bad for immediately opening a new one but... yeah, here we are.

The bugfix to #119 appears to work quite lovely and redstone now travels as expected regardless of direction!

However, I noticed something strange when I tried firing up my repeater clock contraption with the simple 1-tick pulse contraption I made. It wasn't firing up the clock! I had to make the pulse last for 2 ticks so that it would work as expected.

Of course, this surely has to do with the new code introduced to fix the more major issue of redstone ticking, and this is definitely a smaller edge case but anyway, here is some footage of it in action.

Redstone dust is powered by 1-tick pulse, and the note block is triggered, but is not considered "powered" and does not transmit power to repeaters - is this intended behavior?: https://www.youtube.com/watch?v=sEVrBr7UFm4

It appears that repeaters are no longer fired up by 1-tick redstone pulses: https://www.youtube.com/watch?v=VTBuE667zj8&feature=youtu.be

I rotated the 1-tick contraption so the 1-tick pulse goes out in different orientations, and iredstone does indeed behave slightly differently depending on direction: https://www.youtube.com/watch?v=WD2WaMs3Ox0

This is the [blueprint ](https://drive.google.com/drive/folders/1wug4qJaAWTLThgoqf8A3MSBcQhPU8ofM?usp=share_link) of the 1-tick pulse contraption used for testing. Please place it on top of a redstone plate or it will power the block beneath and it won't work right.

**Comment by dannydjdk** [comment]
Thanks for the detailed report and the blueprint. No need to feel bad for finding bugs for me. ;). In retrospect, I probably should have released yesterday's update as a beta due to its potential to affect existing circuits.

In any case, I should be able to nail this down this evening. Interestingly, one of my test cases is pretty similar to this, but I only tested it in one direction. The 119 fix was supposed to eliminate the direction-based differences, but it looks like it may have introduced a new one.

**Comment by dannydjdk** [comment]
Well, instead of fixing this last night, I got sick.

So far, it appears that the issue is with the observer. I didn't change the observer in the last update, so it likely still has the previous bug, and now that the repeater doesn't, they're out of sync with each other. Should be an easy fix once I can sit up long enough to do it.

**Comment by FoxyFox909** [comment]
Hope you feel better soon

**Comment by dannydjdk** [comment]
Fix is now live for latest Tiny Redstone versions for Minecraft 1.16.5, 1.18.2, 1.19.2 and 1.19.3.
