### ISSUE TITLE
Panel powering other panel like a solid block?

### ISSUE THREAD

**Issue by Souse2188** [dannydjdk/Tiny-Redstone#126]
those two lamps are being powered by sheer will power alone

![2023-04-17_14 55 44](https://user-images.githubusercontent.com/97354891/232382590-60381d9c-c2fa-4a10-8d66-4d43c7298c61.png)

**Comment by dannydjdk** [comment]
It's difficult to troubleshoot based on this screenshot, but if those lamps are at the top of the blockspace, they will pick up redstone being output from the block above them. Because the panels are in different orientations, they just pick up the redstone output of the whole block. (see #114)

I would recommend not using panels at all or just using the bottom panels. They aren't really necessary.

**Comment by dannydjdk** [comment]
Closing as duplicate. See #114
