### ISSUE TITLE
Crash involving PanelTile.updateVoxelShape

### ISSUE THREAD

**Issue by sreegs-ahuj9** [dannydjdk/Tiny-Redstone#133]
Hi there, we're encountering a crash on our server. Looks like a null exception involving concurrent access on a hashmap based on the [line of the crash](https://github.com/dannydjdk/Tiny-Redstone/blob/9af880baa247f484b2ec97ebda8ba641254a5d47/src/main/java/com/dannyandson/tinyredstone/blocks/PanelTile.java#L1423). Unfortunately I don't know much minecraft or java concurrency or else I'd just make a PR. I've attached a crash report
[crash-2024-02-11_13.12.46-client.txt](https://github.com/dannydjdk/Tiny-Redstone/files/14233972/crash-2024-02-11_13.12.46-client.txt)

We're running MC 1.20.1 via curseforge, also Create. The crash happens when a Create train activates a tiny redstone block with a panel.

**Comment by dannydjdk** [comment]
Thanks for the report! I have a few questions.

This looks like a client side crash. Is the server also crashing?

According to the log, it looks like Create might be trying to do something with the VoxelShape at the same time that Tiny Redstone is attempting to update it. When you say "activates", do you mean it's just giving it a redstone signal, or is it trying to make it apart of a contraption?

Does this happen intermittently, or is it consistently repeatable?

**Comment by sreegs-ahuj9** [comment]
When it gives it a redstone signal. Someone was using a Tiny Redstone component in a circuit that is activated when a train trips a train signal, which sends out a redstone pulse.

It did not crash the server, just the client, and it happened consistently

**Comment by dannydjdk** [comment]
I've posted a new version of the mod that will hopefully fix this issue (https://www.curseforge.com/minecraft/mc-mods/tiny-redstone/files/5189392). I can't verify 100%, because I was unable to reproduce, and the crash report appears to be incorrect about the line number where the crash occurs. There is no iterating happening at that point. I made some adjustments to that function where iteration is actually happening.

If you could test with this version and let me know what happens, I would be most grateful!

**Comment by krze** [comment]
Thank you! I'll give this a try and report back if we still encounter the crash.

**Comment by sreegs-ahuj9** [comment]
Thank you! I'll install the update on our server and report back if we still get the crash.

**Comment by dannydjdk** [comment]
Fix back-ported to 1.19.2
