### ISSUE TITLE
[feature request] 3d torch

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#2]
So that it fits in with the other components. A 2d torch looks strange.

Already on your to-do list

**Comment by dannydjdk** [comment]
The truth is, I am an experienced software developer, but I'm not very experienced with rendering models. That's why the 2d torch exists. 😉 Because I want to render the torch on an angle in order to show its directionality, this one is particularly difficult for me. Once I figure it out though, I can stop avoiding implementation of the Tiny Lever.

**Comment by lublak** [comment]
I'm also a developer. Unfortunately, I lack the complete knowledge about Minecraft mod development. Some things can be derived, but some things, especially when it comes to rendering, my head also glows.

**Comment by dannydjdk** [comment]
Released with 1.16.5-1.5.0b
