### ISSUE TITLE
[bug] piston sometimes fires twice (visual)

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#37]
Sometimes the pistons are triggered twice (sound, rendering).

**Comment by dannydjdk** [comment]
Possibly a sync issue. The client is probably losing the "extended" status briefly while it processes the sync from the server.

Just to be clear, you're talking about a really fast flutter, right? Have you noticed any particular circumstances when it happens more frequently?

**Comment by lublak** [comment]
Yes, I'm talking about a little cough like that. I haven't noticed any real problems at the moment. I also assume that the server and client are briefly out of sync.

**Comment by dannydjdk** [comment]
I noticed this also occurs with observer outputs every once in a while. If I output the signal to redstone dust outside the panel, I can see that it's only a panel render issue that's not affecting the output.
I am planning to clean up the syncing process which should fix this. Currently, it's syncing real time whenever any event causes a change in state that the client needs to know about. This could be a player interaction, a neighbor change or a tick event. My plan is to use a sync flag to have it queue up a sync at the end of the tick method if anything happened since the last tick that requires a sync. I think that will reduce the frequency of syncs while maintaining real time visuals.

**Comment by dannydjdk** [comment]
This commit seems to significantly reduce the flutter, but it doesn't eliminate it entirely.
