### ISSUE TITLE
[bug] you can place panels agains grass and the grass gets removed

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#62]
![java_u5H1P14A7X](https://user-images.githubusercontent.com/44057030/117556443-740d1080-b069-11eb-9bb3-c0e9ab7ca49e.png)
![java_F8sWETS8tp](https://user-images.githubusercontent.com/44057030/117556445-75d6d400-b069-11eb-8b97-890a2b4c9a74.png)

**Comment by dannydjdk** [comment]
Isn't this normal vanilla behavior? I'm not doing anything special for block placement.

**Comment by dannydjdk** [comment]
![2021-05-10_00 13 24](https://user-images.githubusercontent.com/17087603/117609064-e5f66000-b124-11eb-8041-c10cdb3dd388.png)
![2021-05-10_00 13 42](https://user-images.githubusercontent.com/17087603/117609068-e858ba00-b124-11eb-8ac0-3d75d68e3a5a.png)

The only thing that might be unexpected is the facing direction of the panel, which is due to the fact that it's based on the side of the grass clicked. Do you think this a big enough problem to justify changing the facing calculations?

**Comment by lublak** [comment]
It's just very very unusual. But well, there is currently no vanilla minecraft block that can be placed on the side of a grass block. But I think it's okay like that.
