### ISSUE TITLE
Tiny Sticky Piston successfully pulls block back on short pulse

### ISSUE THREAD

**Issue by dannydjdk** [dannydjdk/Tiny-Redstone#70]
From the Minecraft wiki:

> In Java Edition, pistons finish extending early and start retracting if given a pulse shorter than 3 game ticks (1.5 redstone ticks; 0.15 seconds). These shorter pulses cause sticky pistons to "drop" their block, leaving it behind when trying to push it with a short pulse. Also, this causes the block to end up in its final position earlier.

This is arguably a bug in vanilla piston behavior, but it is behavior that some circuits rely on. What seems to happen in vanilla is that the piston starts to retract before it finishes pushing, so when it looks for a block to pull back, it doesn't find one, because the block is still being pushed. In Tiny Redstone, the pushing and pulling of tiny blocks happens instantly, so no matter how quick the pulse is, it will push and then pull it back. I guess it shouldn't do this. *sigh*

**Comment by lublak** [comment]
If you declare a bug as a feature, it is no longer a bug. xD

**Comment by DaveJWalker** [comment]
I came here to report this same issue and found that it's already been reported.  They're probably not needed, but I created a couple of screenshots showing the behavior difference between vanilla and tiny redstone:

![2021-06-04_21 41 16](https://user-images.githubusercontent.com/83719612/120880239-efd17e80-c57d-11eb-93f6-ba418c13a26e.png)

![2021-06-04_21 41 22](https://user-images.githubusercontent.com/83719612/120880244-f52ec900-c57d-11eb-941b-f067fb33295a.png)

In my view, it may have started as a bug, but it has since become a feature.  It's been around a long time, lots of common circuits depend on it, and it's unlikely to change going forward.  Since it's a commonly used mechanism in redstone circuits, I personally feel it shouldn't be a low priority item.

My 2 cents...

**Comment by dannydjdk** [comment]
Thanks for the feedback @DaveJWalker. One of the reasons I tagged it low priority is because no one else reported it, so I figured no one cared. I'll remove the tag based on your feedback.

**Comment by dannydjdk** [comment]
Fix released in version 1.16.5-1.8.3

Fixing obscure anomalies like this is pretty difficult, but I discovered that adding them is even more difficult. I spent so much time considering the best approach to this, and in the end, it only required 32 characters of code. 😝
