### ISSUE TITLE
Server start up crash with Jade

### ISSUE THREAD

**Issue by Theoretical-Enday** [dannydjdk/Tiny-Redstone#77]
I update Jade mod 2.7.2 from 2.7.1.Then server can't start up.
Forge 1.16.5 36.2.2 Tinyredstone 1.8.3 Jade 2.7.2(crash)2.7.1(normal)
When I give feedback to Jade,told me report this to tinyredstone author.
https://github.com/Snownee/Jade/issues/60

**Comment by dannydjdk** [comment]
Thanks for reporting this! This should be fixed with Tiny Redstone 1.16.5-1.9.1.

For some reason, Hwyla (and Jade) attempt to load plug-ins on the server side as well as client side, even though GUI components can't be loaded server side. In the past, Hwyla and Jade would just catch these exceptions and move on, but with the recent Jade update, it's letting them crash. I don't know enough about hwyla to know if there's actually a good reason to be loading plug-ins server side, but I do know that for Tiny Redstone, it's completely unnecessary. So, Tiny Redstone is now just catching the exception that Jade used to catch.

Please let me know if this fixes the issue for you.

**Comment by Theoretical-Enday** [comment]
1.9.1 fix it ,thanks your excellent mod!
