### ISSUE TITLE
[feature request] 3d space

### ISSUE THREAD

**Issue by lublak** [dannydjdk/Tiny-Redstone#8]
Allow the circuit to go up.
- allow pistons to push blocks upwards
- allow dust on blocks
- allow blocks on blocks
- allow blocks over torches
- allow redstone signal
- allow an output of the redstone signal upwards
- etc...

Currently, most logic can be implemented in 1-height circuits.
I think, especially for performance and maintainability, it will be rather impossible.

a simpler idea would be the two feature requests:
https://github.com/dannydjdk/Tiny-Redstone/issues/10
https://github.com/dannydjdk/Tiny-Redstone/issues/9

**Comment by dannydjdk** [comment]
I have mixed feelings about this not only due to the significant increase is programmatic complexity, but also that it may make things more confusing for players. The alternatives you mention are definitely more likely to be implemented. On the other hand, one of my main aims with this mod was to behave as close to vanilla redstone as possible. If you know how to build something in vanilla redstone, I want you to be able to apply that same knowledge to Tiny Redstone.

One of the reasons I made the torches directional and to work independently as NOT gates was to account for the 2d-ness of the panel.

One possible thought is to just allow a second layer to put redstone on blocks and blocks over torches, but with the logic required for that, it might not be a big stretch to just allow arbitrary height (up to 7 within the block space).

I'll revisit this idea once I have the main 2d functionality where I want it.

**Comment by lublak** [comment]
Year ... It is like a double-edged sword.
I also assume that most circuits will be built in 2d anyway.
Currently, I do not know which circuit could not be built in 2d.
True, it was an idea. But whether it makes sense I don't really know.

**Comment by Fireztonez** [comment]
I understand your idea to try keeping Tiny Redstone as closed as possible to Vanilla redsone.
But I can see several cases where it is impossible or really complicated to make a compact redstone circuit without 3d space or at least colored redstone. For sure a big 3d circuit is a lot harder to work on than a simple 2d circuit, but in somes cases you can have to make more complex circuit question to being able to do what you want.

In any case, think about it and I will follow the updates of your mod carefully!

**Comment by dannydjdk** [comment]
Issues to resolve:

- [ ] Response to redstone signals above and below panel are not finalized and are currently inconsistent. Some decisions need to be made here.
- [ ] A few tiny components, especially those that can not be placed vertically, have no bottom texture.
- [ ] All components can float in 3d space including Tiny Redstone Dust, Repeaters and Torches.
- [ ] Tiny Buttons and Levers can only be oriented on the bottom of a cell for backward compatibility.
- [ ] Placement can be frustrating, because most components have an activation on right click, so it's necessary to sneak when placing many components. And, facing pistons downward is quite difficult. We may need some kind of placement "mode" that prevents activation when trying to place components on top of other components.
- [ ] One Probe not getting all info when looking at the side of a component, possibly because the segment isn't being calculated.
- [ ] One Probe not giving any useful info when looking at the side of the panel.
- [ ] Thinking too much about orientations and facings and the translations thereof can cause a brain crash.

**Comment by dannydjdk** [comment]
Closing this issue. 3d is now live and functional. A couple minor issues remain and have been given issues of their own: #60, #59.
