### ISSUE TITLE
[feature request] A Drill or a way to interact with the block below

### ISSUE THREAD

**Issue by wooby6** [dannydjdk/Tiny-Redstone#86]
we currently have Tiny Redstone interaction in 5 Directions: North, South, East, West, & Up
But not **Down**

**Comment by dannydjdk** [comment]
Thanks for the suggestion! There are a couple of options that may eliminate the need for this.

One, you can place panels on walls and ceilings. In those orientations, it is possible to interact with the block below. You will then be unable to interact with whatever side the panel is placed against.

The second option is currently in development. That is panel free placement (#53). You will soon(ish) be able to place tiny redstone components in world without a panel. The idea of the panel, then, would be to insulate the circuit from the block below (otherwise, any redstone signal in that block will power every redstone dust touching the block).

A similar idea had been proposed before (#10). After some discussion, we decided against it, mostly because of the panel-free placement idea, vertical placement and 3d circuits, none of which existed at that time.

In any case, we can leave this issue open for consideration and discussion until we get a chance to play around with panel-free placement and see if it sufficiently fulfills this need.

**Comment by dannydjdk** [comment]
I'm closing this as I believe there is no longer a need for this. Feel free to comment if you object.
